name: Deploy

on:
  push:
    tags:
      - '*'

jobs:
  build-wheel-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: RalfG/python-wheels-manylinux-build@v0.3.1-manylinux2014_x86_64
        with:
          python-versions: 'cp37-cp37m cp38-cp38 cp39-cp39'
          #build-requirements: 'cython numpy'
          system-packages: 'epel-release'
          pre-build-command: 'yum -y install python3-pybind11'
      - name: Upload wheel
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
  build-wheel-matrix:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [macos-10.14, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - uses: actions/checkout@master
        name: checkout pybind
        with:
          repository: pybind/pybind11
          path: pybind11
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: setup xcode version
        if: startsWith(matrix.os, 'macos')
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '10'
      - name: Build
        run: |
          pip install wheel
          python setup.py bdist_wheel
      - name: Upload wheel
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: [build-wheel-linux, build-wheel-matrix]
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: Get Branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          echo ::set-env name=branch::$branch
      - name: Print branch name
        run: |
          echo ${{ env.branch }}
      - name: Load artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Remove linux_x86_64 wheels
        run: rm dist/*-linux_x86_64.whl
      - name: Publish distribution package to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.pypi_user }}
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish distribution package to PyPI
        #if: env.branch == 'master'
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.pypi_user }}
          password: ${{ secrets.pypi_password }}